version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version
      - mvn -version

  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - target/*.war

