version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain devops --domain-owner 545009846899 --region us-east-1 --query authorizationToken --output text`
  build:
    commands:
      - echo Build started on 'date'
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn -s settings.xml package
artifacts:
  files:
    '**/*'




